const int abcclass_flash_geom_Rectangle = 0;
const int abcclass_flash_geom_Point = 1;
const int flash_display_Loader_content_get = 57;
const int flash_display_Loader_contentLoaderInfo_get = 58;
const int abcclass_flash_display_Loader = 2;
const int flash_display_MovieClip_currentFrame_get = 68;
const int flash_display_MovieClip_framesLoaded_get = 69;
const int flash_display_MovieClip_totalFrames_get = 70;
const int flash_display_MovieClip_trackAsMenu_get = 71;
const int flash_display_MovieClip_trackAsMenu_set = 72;
const int flash_display_MovieClip_play = 73;
const int flash_display_MovieClip_stop = 74;
const int flash_display_MovieClip_nextFrame = 75;
const int flash_display_MovieClip_prevFrame = 76;
const int flash_display_MovieClip_gotoAndPlay = 77;
const int flash_display_MovieClip_gotoAndStop = 78;
const int flash_display_MovieClip_addFrameScript = 79;
const int flash_display_MovieClip_scenes_get = 80;
const int flash_display_MovieClip_currentScene_get = 81;
const int flash_display_MovieClip_currentLabel_get = 82;
const int flash_display_MovieClip_currentFrameLabel_get = 83;
const int flash_display_MovieClip_prevScene = 85;
const int flash_display_MovieClip_nextScene = 86;
const int flash_display_MovieClip_enabled_get = 87;
const int flash_display_MovieClip_enabled_set = 88;
const int flash_display_MovieClip_isPlaying_get = 89;
const int abcclass_flash_display_MovieClip = 3;
const int abcpackage_Point_as = 0;
const int abcpackage_Loader_as = 1;
const int abcpackage_MovieClip_as = 2;
const int abcpackage_Rectangle_as = 3;
extern const int ./abc1a.abc_abc_length;
extern const int ./abc1a.abc_abc_method_count;
extern const int ./abc1a.abc_abc_class_count;
extern const int ./abc1a.abc_abc_script_count;
extern const unsigned char ./abc1a.abc_abc_data[];
